name = "Faker"
uuid = "0efc519c-db33-5916-ab87-703215c3906f"
repo = "https://github.com/codeneomatrix/Faker.jl.git"
version = "0.2.2"

[deps]
YAML = "ddb6d928-2868-570f-bddf-ab3f9cf99eb6"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[compat]
julia = "1"